### ISSUE TITLE
Segmentation Fault on WAV Recognition Using vibra Command

### ISSUE THREAD

**Issue by Sever-IN** [BayernMuller/vibra#8]
./vibra --recognize --wav in.wav > result.json
[1]    10463 segmentation fault (core dumped)  ./vibra --recognize --wav in.wav > result.json

there are also compilation warnings:
`mkdir build && cd build                         
cmake ..
make
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (0.7s)
-- Generating done (0.0s)
-- Build files have been written to: /home/sever-in/vibra/build
[ 12%] Building CXX object CMakeFiles/vibra.dir/cli/main.cpp.o
[ 25%] Building CXX object CMakeFiles/vibra.dir/cli/cli.cpp.o
/home/sever-in/vibra/cli/cli.cpp: In constructor ‘CLI::CLI(int, char**)’:
/home/sever-in/vibra/cli/cli.cpp:43:18: warning: catching polymorphic type ‘class args::Help’ by value [-Wcatch-value=]
   43 |     catch (args::Help)
      |                  ^~~~
/home/sever-in/vibra/cli/cli.cpp:48:29: warning: catching polymorphic type ‘class args::ParseError’ by value [-Wcatch-value=]
   48 |     catch (args::ParseError e)
      |                             ^
/home/sever-in/vibra/cli/cli.cpp:56:34: warning: catching polymorphic type ‘class args::ValidationError’ by value [-Wcatch-value=]
   56 |     catch (args::ValidationError e)
      |                                  ^
[ 37%] Building CXX object CMakeFiles/vibra.dir/fingerprinting/algorithm/signature.cpp.o
[ 50%] Building CXX object CMakeFiles/vibra.dir/fingerprinting/algorithm/frequency.cpp.o
[ 62%] Building CXX object CMakeFiles/vibra.dir/fingerprinting/algorithm/signature_generator.cpp.o
[ 75%] Building CXX object CMakeFiles/vibra.dir/fingerprinting/audio/wav.cpp.o
In file included from /usr/include/c++/13/bits/shared_ptr.h:53,
                 from /usr/include/c++/13/memory:80,
                 from /home/sever-in/vibra/fingerprinting/audio/wav.h:6,
                 from /home/sever-in/vibra/fingerprinting/audio/wav.cpp:1:
In constructor ‘std::__shared_count<_Lp>::__shared_count(_Ptr) [with _Ptr = unsigned char*; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’,
    inlined from ‘std::__shared_count<_Lp>::__shared_count(_Ptr, std::false_type) [with _Ptr = unsigned char*; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’ at /usr/include/c++/13/bits/shared_ptr_base.h:928:22,
    inlined from ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(_Yp*) [with _Yp = unsigned char; <template-parameter-2-2> = void; _Tp = unsigned char; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’ at /usr/include/c++/13/bits/shared_ptr_base.h:1469:17,
    inlined from ‘std::shared_ptr<_Tp>::shared_ptr(_Yp*) [with _Yp = unsigned char; <template-parameter-2-2> = void; _Tp = unsigned char]’ at /usr/include/c++/13/bits/shared_ptr.h:214:46,
    inlined from ‘Wav::Wav(const char*, uint32_t, uint32_t, uint32_t, uint32_t)’ at /home/sever-in/vibra/fingerprinting/audio/wav.cpp:32:18:
/usr/include/c++/13/bits/shared_ptr_base.h:921:15: warning: ‘void operator delete(void*)’ called on pointer returned from a mismatched allocation function [-Wmismatched-new-delete]
  921 |               delete __p;
      |               ^~~~~~~~~~
/home/sever-in/vibra/fingerprinting/audio/wav.cpp: In constructor ‘Wav::Wav(const char*, uint32_t, uint32_t, uint32_t, uint32_t)’:
/home/sever-in/vibra/fingerprinting/audio/wav.cpp:32:72: note: returned from ‘void* operator new [](std::size_t)’
   32 |     mData = std::shared_ptr<std::uint8_t>(new std::uint8_t[raw_pcm_size]);
      |                                                                        ^
In constructor ‘std::__shared_count<_Lp>::__shared_count(_Ptr) [with _Ptr = unsigned char*; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’,
    inlined from ‘std::__shared_count<_Lp>::__shared_count(_Ptr, std::false_type) [with _Ptr = unsigned char*; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’ at /usr/include/c++/13/bits/shared_ptr_base.h:928:22,
    inlined from ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(_Yp*) [with _Yp = unsigned char; <template-parameter-2-2> = void; _Tp = unsigned char; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’ at /usr/include/c++/13/bits/shared_ptr_base.h:1469:17,
    inlined from ‘std::shared_ptr<_Tp>::shared_ptr(_Yp*) [with _Yp = unsigned char; <template-parameter-2-2> = void; _Tp = unsigned char]’ at /usr/include/c++/13/bits/shared_ptr.h:214:46,
    inlined from ‘void Wav::readWavBuffer(std::istream&)’ at /home/sever-in/vibra/fingerprinting/audio/wav.cpp:128:26:
/usr/include/c++/13/bits/shared_ptr_base.h:921:15: warning: ‘void operator delete(void*)’ called on pointer returned from a mismatched allocation function [-Wmismatched-new-delete]
  921 |               delete __p;
      |               ^~~~~~~~~~
/home/sever-in/vibra/fingerprinting/audio/wav.cpp: In member function ‘void Wav::readWavBuffer(std::istream&)’:
/home/sever-in/vibra/fingerprinting/audio/wav.cpp:128:77: note: returned from ‘void* operator new [](std::size_t)’
  128 |             mData = std::shared_ptr<std::uint8_t>(new std::uint8_t[mDataSize]);
      |                                                                             ^
[ 87%] Building CXX object CMakeFiles/vibra.dir/communication/shazam.cpp.o
[100%] Linking CXX executable vibra
[100%] Built target vibra
`

**Comment by BayernMuller** [comment]
@Sever-IN, I apologize for the issue.

Could you please send me the WAV file you tested to my email at cjjunk29@gmail.com? I believe the file will help me with debugging.

Thank you!

**Comment by BayernMuller** [comment]
```bash
vibra --recognize --wav ~/Downloads/in.wav | jq .track.share.text
"ANGEL VOICES par Virtual Self"
```

@Sever-IN I have tested Vibra with the file you sent, but I was unable to replicate the issue you mentioned.

Could you provide your system information? Specifically, your OS and CPU architecture?

I will test Vibra on a virtual machine with the same system configuration as yours.

**Comment by Sever-IN** [comment]
@BayernMuller I'm using ubuntu 24.04 LTS with an AMD64 based processor, I think the problem may be with libcurl or libfftw3

**Comment by BayernMuller** [comment]
I just fixed the segmentation fault issue with [this commit](https://github.com/BayernMuller/vibra/commit/071cf59a2113f8b1ba2541dabd9635eb1da7244e). The problem was related to libcurl and a double-free corruption involving its callback function argument.
